name: Generate LeetCode Stats SVG

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LEETCODE_USERNAME: 'matthewhan'
      LEETCODE_US_USERNAME: 'MatthewHan'

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 禁用默认 GITHUB_TOKEN

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Generate LeetCode SVG & metadata
      - name: Generate LeetCode SVG
        run: |
          node scripts/generate_svg.js
          echo "已为用户 ${LEETCODE_USERNAME} 生成统计卡片 SVG"

      # 5. Commit & push only when solved count increases
      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT }}
        run: |
          git config user.name "matthew-han"
          git config user.email "837204579@qq.com"
          # 从上一次提交中读取旧的 totalSolved（如果文件不存在则为 0）
          old_total=$(git show HEAD:stats/${LEETCODE_USERNAME}.json 2>/dev/null | node -pe "try{(JSON.parse(require('fs').readFileSync(0,'utf8')).totalSolved)||0}catch(e){0}" || echo 0)

          # 读取新元数据（脚本已生成到 stats）
          new_json="stats/${LEETCODE_USERNAME}.json"
          if [ ! -f "$new_json" ]; then
            echo "未找到元数据 JSON，跳过提交。"
            exit 0
          fi
          new_total=$(cat "$new_json" | node -pe "try{(JSON.parse(require('fs').readFileSync(0,'utf8')).totalSolved)||0}catch(e){0}" 2>/dev/null || echo 0)

          echo "旧的 totalSolved: $old_total | 新的 totalSolved: $new_total"

          # 仅当解题数增加时才提交（同时包含 SVG 与 JSON）
          if [ "$new_total" -gt "$old_total" ]; then
            git add stats
            if ! git diff --cached --quiet; then
              git commit -m "chore: update leetcode stats (totalSolved $old_total -> $new_total)"
              git push https://${PAT_TOKEN}@github.com/Matthew-Han/leetcode-stats-card.git HEAD:main
            else
              echo "没有需要提交的文件变更。"
            fi
          else
            echo "解题数未增加，跳过推送。"
          fi
